version: "3"
services:
  chromedriver:
    container_name: chromedriver
    build: .
    command: "tail -f /etc/hosts"
    volumes:
      - ./build:/opt
    environment:
      FONTCONFIG_FILE: /opt/.fonts/fonts.conf
      FONTCONFIG_PATH: /opt/.fonts
